// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hrbyojdxsnrhhwydsbeb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhyYnlvamR4c25yaGh3eWRzYmViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1ODg1MDQsImV4cCI6MjA3MDE2NDUwNH0.zyQNTTUixnNNNattHPHXzIJCR6JCXLKrrYGG57LkMUA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});